# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hackerspace Blumenau
email: your-email@domain.com
description: Um espaço comunitário, aberto e colaborativo com disponibilização de uma infraestrutura para realização de encontros, eventos e oficinas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hackerspaceblumenau.github.io" # the base hostname & protocol for your site
permalink: '/:slug.html'

collections:
  projects:
    output: true
  sitepages:
    output: true

# Social settings
slackin: "https://hackerspacebnu.herokuapp.com"
slack_username: hackerspaceblumenau
github_username: HackerspaceBlumenau
googlegroup_username: hackerspace-blumenau
# twitter_username: HackerspaceBlumenau
facebook_username: hackerspace.blumenau
googleplus_username: HackerspaceBlumenau

# Build settings
markdown: kramdown
timezone: 'America/Sao_Paulo'
