name: Hugo Publish
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Print theme commit hash
        run: cd ./themes/iara && git log --oneline

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify --cleanDestinationDir --gc --baseURL https://www.hackerspaceblumenau.org

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   # if: github.ref == 'refs/heads/master'
      #   with:
      #     github_token: ${{ secrets.HUGO_GH_TOKEN }}
      #     publish_dir: ./public
