name: Hugo Publish Dry Run
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Update theme to latest commit
        run: cd ./themes/iara && git clean -ffdx && git reset --hard HEAD && git pull origin master

      - name: Publish
        uses: chabad360/hugo-gh-pages@master
        with:
          # Remember to set this as a secret (i.e. secrets.HUGO_GH_TOKEN).
          # Don't forget to set the secret value in the project settings.
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # Use if you have a custom domain for your site.
          cname: hackerspaceblumenau.net.br
          # Use if your site is not hosted on the gh-pages branch.
          branch: gh-pages-dryrun
          # Use if your pushing to a different repo.
          # Dont add ".git" to the end of the URL (youl'll get 404s).
          # repo: you/you.github.io
          # Use if your site requires a specific version of Hugo.
          # Append "extended_" to the begining to use Hugo Extended.
          hugoVersion: extended_0.110.0
          # Use if you want to pass some custom arguments to Hugo.
          args: --gc --cleanDestinationDir --minify
          # Use this if your site isn't in the root of your repo.
          # The root of your repo can be found at /github/workspace
          # siteDir: /github/workspace/site
